# Generated by Django 5.2 on 2025-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emp',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_ret',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
