# Generated by Django 5.2 on 2025-04-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_alter_emprunt_date_emp_alter_emprunt_date_ret'),
        ('livres', '0009_remove_emprunt_livre_remove_emprunt_membre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livres.livre'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emprunts.membre'),
        ),
    ]
