# Generated by Django 5.2 on 2025-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0004_alter_avis_livre_alter_avis_membre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
