# Generated by Django 5.2 on 2025-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0005_alter_avis_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
