# Generated by Django 5.2 on 2025-04-22 07:21

import livres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_categorie_alter_livre_auteur_alter_livre_createur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, related_name='livre', to='livres.categorie'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[livres.models.validate_isbn]),
        ),
    ]
