# Generated by Django 5.2 on 2025-04-22 08:15

import livres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_alter_livre_categorie_alter_livre_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[livres.models.validate_isbn]),
        ),
    ]
