# Generated by Django 5.2 on 2025-04-25 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_alter_livre_isbn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=10)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emp', models.DateField()),
                ('date_ret', models.DateField()),
                ('retourne', models.DateField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=5000, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.membre')),
            ],
        ),
    ]
