# Generated by Django 5.2 on 2025-04-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0007_membre_emprunt_avis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='users',
            new_name='user',
        ),
    ]
