# Generated by Django 5.2 on 2025-04-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0008_rename_users_membre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
